### ISSUE TITLE
Consideration for fasttext

### ISSUE THREAD

**Issue by chris-ha458** [allenai/peS2o#3]
I am wondering if any consideration for fasttext have been made.

First of all it can provide much more languages.
The basic version available on their site provides [176 languages in either a 150MiB or 1MiB(quantized) package](https://fasttext.cc/docs/en/language-identification.html)
Secondly, compared to `gcld3` it is more actively maintained
The codebase itself is forked for development by other parties [fastertext](https://github.com/kpu/fasterText)
and even [facebook recently released a new model](https://github.com/kpu/fasterText) that extends language support into 200 languages.
[3rd party models](https://github.com/laurieburchell/open-lid-dataset) are available as well

**Comment by soldni** [comment]
Hi @chris-ha458!

While I agree that fasttext is generally better than cld3, I did not notice any meaningful difference for this application when I compared the two. However, we might reconsider for the next release! Thanks.

**Comment by chris-ha458** [comment]
I guess for the purpose of rejecting non-english it is not that meaningful.
I hope to see this be extended multilngually either by the original developers or other opensource developers so hoped to leave the info.
